travis:
  secure:
    BINSTAR_TOKEN: Q36l0Lt/90XRmY2kcuc14SjritkyL0L6Kn/J7YQk0+jnXMmWq5xWdA1wSdhjDHAJllqFCvpXHHFRtUJCWAlX+zTMAdX8GwKgRQD7uW7+/fhkyf+v0Z3WlQgDPYgahmuTQiOY95UConZWnoIAk76akDI8KcyMNhA5Y58PxN+WcL9mT/2drHqt4RCiV6RK8TdDcP8vSEZl/C5heCm2SHwwkCVpB+mjLEUkyncXf29eE3IpODSSPx4zFoW80DI0t5mqkaQdoyQvP0d6MIr14i2ICvYBmciq4jKdLr9BySUk7/rCOnkvmEk4vSNRFBgLMOpkpxaf7mu+fGKhhvvaPKTROOJRdU8lVOKr0IkZ7Er+byXuIXy631PKaI4+CWPbkCnUGHWF17ekK+D0MvxsHgHvmBr0h2nbZcR8MTPmm0CcmuvvAOq+j5yYFhB8XAWjHkHmHjCvrrFX5sGZRsQ8aWB5lmaTNhpqegJ95VI3usx/IwXfNov/VEdIZ7f75O5BONPVb8YwKnRmh7BAeuiiYVil2w4RXiaXD6sn+7Q+avj/S25ZauZ57LQCE91L49oNkCf6HAHAvTtjFu+f9p9YfM6o3JRCXa1CBBly50Ga0VqRu6f4m9HJ9rJGY4m5Jfr0masTynWhZz6szp1BvRBdGbi1mbkzeLxc/QW3JpfF1T6rNKU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
